### ISSUE TITLE
Where are the image files?

### ISSUE THREAD

**Issue by letsalllovelain** [The-f6X/Gen4OverlayScript#33]
Is there anywhere I can download it? doesnt seem to come with the code or be linked anywhere.

**Comment by shawnrc** [comment]
Hey, sorry for the late response. We can't keep any images here because we don't own any images of Pokemon! 😅 Distributing image assets we don't own the copyright to is no bueno, so the code is designed to work with any images you can supply numbered 0-649 (the highest-numbered Pokemon in Gen 5). 

This is probably not the answer you were looking for, but there are all kinds of image sets of Pokemon suitable enough for personal use that can be found via Google; try looking for one that matches your personal aesthetic! Best of luck!
